version: "3.9"

services:
  frontend:
    build: .
    image: vedic-app-frontend:latest
    container_name: vedic-app-frontend
    ports:
      - "3000:4173"
  frontend-tests:
    image: node:24
    working_dir: /app
    volumes:
      - .:/app
    user: "${UID:-0}" # This will use your Windows user
    command: npm test
