version: "3.9"

services:
  frontend:
    build: .
    container_name: vedic-app-frontend
    ports:
      - "3000:80"

  frontend-tests:
    image: node:24
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm test"
    depends_on:
      - frontend
    environment:
      - API_URL=http://frontend:80
